#!/bin/bash

# PROGNAME=$(basename $0)
# RELEASE="Revision 1.0.0"
# AUTHOR="(c) 2020 Paul Bargewell (paul.bargewell@opusvl.com)"
# LICENSE="SPDX-License-Identifier: AGPL-3.0-or-later"

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${SYMPA_POSTGRES_USER} WITH ENCRYPTED PASSWORD '${SYMPA_POSTGRES_PASSWORD}' CREATEDB;
    CREATE DATABASE ${SYMPA_DATABASE} OWNER=${SYMPA_POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${SYMPA_DATABASE} TO ${SYMPA_POSTGRES_USER};
EOSQL